server:
  port: 8080

spring:
  datasource:
    multi-datasource-database1:
      url: jdbc:postgresql://localhost:5437/postgres
      username: ENC(7M2fuNhVxRpyjA/oQudIN8OBORNFkf2H15NY7aUAyl5e6MSZTThle4fysns8Jtg+)
      password: ENC(qVRZj0AKqziwH/QJpMWUxhCskgZxpI3P7Cw/y+9Z0u7E9F+aVC9UraupXgZ2zl1j)
      driver-class-name: org.postgresql.Driver

    multi-datasource-database2:
      url: jdbc:postgresql://localhost:5438/postgres
      username: ENC(XYJfFTfziQJR9T/NMOwjp1duIqboE0mSBTWEq+Gi85cQ4iAigV/iLVnTWTX3hKxu)
      password: ENC(IGyeyPeOVVYAOUpNYnp1a/KhxEjU8AvoRRU5eDGRkJ2qUfGFHsTLPga285IBE5gF)
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false

jasypt:
  encryptor:
    password: changeit